# Generated by Django 4.2.6 on 2024-02-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempts',
        ),
    ]
