# Generated by Django 4.2.6 on 2024-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_quizattempt_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
